#
server:
  address: localhost
  servlet:
    context-path: /

#设置数据库连接信息
spring:
  datasource:
    username: root
    password: 2597
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver

# 设置包含application-dev.properties还是application-pdt.properties
  profiles:
    active: dev

# 查看当前项目中已启用和未启用的自动配置的报告。
debug: true

#AutoConfigure试验
hello:
  msg:wuqingyi

